run:
  timeout: 3m
linters:
  enable:
    - govet
    - errcheck
    - gosimple
    - staticcheck
    - ineffassign
    - goconst
    - gofumpt
    - gocritic
    - revive
issues:
  exclude-use-default: false
